# Generated by Django 3.1.5 on 2021-02-07 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0004_auto_20210205_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 7, 6, 25, 36, 47930, tzinfo=utc)),
        ),
    ]
